// Popular cities and districts in Nepal for reference
// This can be used for autocomplete or suggestions in the future

export const nepalLocations = [
    // Major Cities
    'Kathmandu',
    'Pokhara',
    'Lalitpur',
    'Bhaktapur',
    'Biratnagar',
    'Birgunj',
    'Dharan',
    'Bharatpur',
    'Janakpur',
    'Hetauda',
    'Butwal',
    'Dhangadhi',
    'Nepalgunj',
    'Itahari',
    'Tulsipur',

    // Districts (Alphabetically)
    'Achham',
    'Arghakhanchi',
    'Baglung',
    'Baitadi',
    'Bajhang',
    'Bajura',
    'Banke',
    'Bara',
    'Bardiya',
    'Bhojpur',
    'Chitwan',
    'Dadeldhura',
    'Dailekh',
    'Dang',
    'Darchula',
    'Dhading',
    'Dhankuta',
    'Dhanusa',
    'Dolakha',
    'Dolpa',
    'Doti',
    'Gorkha',
    'Gulmi',
    'Humla',
    'Ilam',
    'Jajarkot',
    'Jhapa',
    'Jumla',
    'Kailali',
    'Kalikot',
    'Kanchanpur',
    'Kapilvastu',
    'Kaski',
    'Kavrepalanchok',
    'Khotang',
    'Lamjung',
    'Mahottari',
    'Makwanpur',
    'Manang',
    'Morang',
    'Mugu',
    'Mustang',
    'Myagdi',
    'Nawalparasi',
    'Nuwakot',
    'Okhaldhunga',
    'Palpa',
    'Panchthar',
    'Parbat',
    'Parsa',
    'Pyuthan',
    'Ramechhap',
    'Rasuwa',
    'Rautahat',
    'Rolpa',
    'Rukum',
    'Rupandehi',
    'Salyan',
    'Sankhuwasabha',
    'Saptari',
    'Sarlahi',
    'Sindhuli',
    'Sindhupalchok',
    'Siraha',
    'Solukhumbu',
    'Sunsari',
    'Surkhet',
    'Syangja',
    'Tanahu',
    'Taplejung',
    'Terhathum',
    'Udayapur'
];

// Helper function to search locations
export const searchNepalLocations = (query) => {
    if (!query) return [];
    const lowerQuery = query.toLowerCase();
    return nepalLocations.filter(location =>
        location.toLowerCase().includes(lowerQuery)
    );
};
